version: "3"

services:
   app:
      container_name: micro-videos-app
      build: .
      command: ./.docker/entrypoint.sh
      environment:
         WAIT_HOSTS: db:3306
         WAIT_HOSTS_TIMEOUT: 300
         WAIT_SLEEP_INTERVAL: 10
         WAIT_HOST_CONNECT_TIMEOUT: 30
      ports:
         - "6000:6000"
      depends_on:
         - db
         - redis
      networks:
         - app-network

   nginx:
      build: .docker/nginx
      container_name: micro-videos-nginx
      restart: always
      tty: true
      ports:
         - "8000:80"
      volumes:
         - .:/var/www
      networks:
         - app-network
      depends_on:
         - app

   db:
      build: .docker/mysql
      container_name: micro-videos-db
      command: --innodb-use-native-aio=0
      restart: always
      tty: true
      ports:
         - 3306:3306
      volumes:
         - ./.docker/dbdata:/var/lib/mysql
      environment:
         - MYSQL_ROOT_PASSWORD=root
         - MYSQL_DATABASE=code_micro_videos
         - MYSQL_USER=root
         - MYSQL_PASSWORD=root
      networks:
         - app-network

   redis:
      image: redis:alpine
      container_name: micro-videos-redis
      expose:
         - 6379
      networks:
         - app-network

networks:
   app-network:
      driver: bridge
