apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 2
  template:
    metadata:
      labels:
        app: goserver
    spec:
      containers:
      - name: goserver
        #if you apply this file with a new version image, you ca use commands like kubectl rollout undo deployment <name of your deployment (here is goserver)>
        image: diegoclair/hello-k8s:v6.1

        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081        # here is the container port "that we start our server.go"
          periodSeconds: 5    # how many time we will await to call the endpoint again
          failureThreshold: 3 # how many time we will call the endpoint and receive failure to consider there has an error with our app
          timeoutSeconds: 1   # how many time we will consider a normal time to wait for the path to response 
          successThreshold: 1 # how many time we will call the endpoint to consider that our app health is ok!

        envFrom:
        - configMapRef:
            name: goserver-env
        - secretRef:
            name: auth-secret
        
        volumeMounts:
          - mountPath: /go/employees
            name: config-employee  #our volume name
            readOnly: true

        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"

      # with this volume we can mount the volume and this file will be created in our pods so the server.go will be able to read the file
      volumes:
      - name: config-employee
        configMap:
          name: configmap-employee
          items:
            - key: members
              path: employee.txt


