# the problem of replicaset is that if we change the docker image to another version, when we reapply the replicaset
# the pods will be yet with the older version and we need to kill all pods so they ca be recreated with the new version
# OBS: the deployment file solve this problem!!
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: goserver
  labels:
    name: goserver
spec: 
  selector:
    matchLabels:
      name: goserver
  replicas: 2
  template:
    metadata:
      name: goserver
      labels:
        name: goserver
    spec:
      containers:
      - name: goserver
        image: diegoclair/hello-k8s:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 8081
