apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
type: Opaque
data:
# here que generate our valus with base64. For example, in the terminal run <echo "diego" | base64>
# base64 can be decoded but this is how the kubernetes work with secret. It has ohters ways to do this more securely..
  USER: ZGllZ28K
  PASSWORD: MTIzNDU2Cg==
