apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule 
metadata:
  name: circuit-breaker-servicex
spec:
  host: servicex-service.default.svc.cluster.local
  trafficPolicy:
    outlierDetection:
      # consecutive5xxErrors will open the circuit breaker even if a internal server error (500) happens (not only if the pod is not responding or slow)
      # we can use other parameters defined by istio, like consecutiveGatewayErrors, consecutiveLocalOriginFailures, etc
      #consecutive5xxErrors: 20 
      consecutiveGatewayErrors: 10
      interval: 20s
      baseEjectionTime: 30s
      maxEjectionPercent: 100