apiVersion: v1
kind: ConfigMap
metadata:
  name: app-conf
data:
  # Here we put all variables that was in our .env file, but we change the
  # values of db host and redis host, to use our services .yaml and we remove
  # de environment of DB_PASSWORD and put in deployment.yaml using our secret pass
  env: |
  
    APP_NAME=challenge01-laravel
    APP_ENV=local
    APP_KEY=base64:eeeeqITM0en1firYp5zUN5to7i8TDj36a1zQBRBgOgU=
    APP_DEBUG=true
    APP_URL=http://localhost

    LOG_CHANNEL=stack

    DB_CONNECTION=mysql
    DB_HOST=mysql-service
    DB_PORT=3306
    DB_DATABASE=laravel
    DB_USERNAME=root

    BROADCAST_DRIVER=log
    CACHE_DRIVER=file
    QUEUE_CONNECTION=sync
    SESSION_DRIVER=file
    SESSION_LIFETIME=120

    REDIS_HOST=redis-service
    REDIS_PASSWORD=null
    REDIS_PORT=6379

    MAIL_MAILER=smtp
    MAIL_HOST=smtp.mailtrap.io
    MAIL_PORT=2525
    MAIL_USERNAME=null
    MAIL_PASSWORD=null
    MAIL_ENCRYPTION=null

    AWS_ACCESS_KEY_ID=
    AWS_SECRET_ACCESS_KEY=
    AWS_DEFAULT_REGION=us-east-1
    AWS_BUCKET=

    PUSHER_APP_ID=
    PUSHER_APP_KEY=
    PUSHER_APP_SECRET=
    PUSHER_APP_CLUSTER=mt1


