apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim   #pv = persistent volume
  labels:
    app: mysql-pv-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi