apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql-server
    tier: db
  ports:
    - port: 3306
  clusterIP: None  # not external access permited, and we can use the name(mysql-service, not by ip) to access the mysql