apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-nginx
  labels:
    app: hello-nginx
spec:
  selector:
    matchLabels:
      app: hello-nginx
  replicas: 2
  template:  # pods
    metadata: 
      labels:
        app: hello-nginx
    spec:
      containers:
      
      - name: hello-nginx
        image: nginx:1.17-alpine
        ports:
        - containerPort: 80

        volumeMounts:
        - mountPath: /etc/nginx/conf.d  # it will replace the original nginx.conf wih our volume
          name: nginx-conf              # name of our volune definition
          readOnly: true

      volumes:                # volume definition
      - name: nginx-conf
        configMap: 
          name: nginx-conf
          items:
          - key: nginx.conf
            path: nginx.conf  # file name with key: nginx.conf content
        