steps:

- id: "Rodando docker-compose"
  name: 'gcr.io/$PROJECT_ID/docker-compose:1.25.5'
  args: ['-f', 'devops/docker/challenge01-laravel/docker-compose.cloudbuild.yml', 'up', '-d']

- id: "Rodando docker ps"
  name: 'gcr.io/cloud-builders/docker'
  args: ['ps']

- id: "Rodando composer"
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec','-t','app','composer','install']

- id: "Copiando .env"
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec','-t','app','cp','.env.example','.env']

- id: "Rodando php key generate"
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec','-t','app','php','/var/www/artisan','key:generate']

- id: "Rodando php cache"
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec','-t','app','php','/var/www/artisan','config:cache']

- id: "Rodando php migrate"
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec','-t','app','php','/var/www/artisan','migrate']

#Running tests  
- id: "Rodando phpunit"
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec','-t','app','php','/var/www/vendor/bin/phpunit','-c','/var/www/phpunit.xml']