apiVersion: apps/v1
kind: Deployment
metadata:
  name:  mysql-server
  labels:
    app:  mysql-server
spec:                     # deployment spec
  selector:               # selector is used to create service
    matchLabels:
      app: mysql-server
      tier: db
  replicas: 1
  
  template:               # POD template
    metadata:
      labels:
        app: mysql-server
        tier: db            # tier: frontend   ; tier: backend...
    spec:                   # POD spec
      containers:
      - image: mysql:5.7
        name: mysql-server
        args:
          - "--ignore-db-dir=lost+found"  
        # when we create a mysql volume in clound, such as azure, gcp, aws.. this my create with a dir lost/found
        # and we need to ignore this folder otherwise we can found problems
        
        env:
        - name: MYSQL_ROOT_PASSWORD
        # how to create a secret password at command line: 
          # kubectl create secret generic mysql-pass --from-literal=password='a1s2d3f4'
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        
        ports:
        - containerPort: 3306
        
        volumeMounts: 
        - name: mysql-persistent-storage            # name of our volume definition
          mountPath: /var/lib/mysql

      volumes: #volume definition
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim  # defined inpersistent-volume.yaml file