apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-hpa
  labels:
    app: go-hpa
spec:
  selector:
    matchLabels:
      app: go-hpa
  replicas: 1
  template:  # pods
    metadata: 
      labels:
        app: go-hpa
    spec:
      containers:

      - name: go-hpa
        image: diegoclair/go-hpa
        ports:
        - containerPort: 80

        resources:
          requests: # minimum necessary
            cpu: 50m
          limits:   # maximum
            cpu: 100m
