apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: go-hpa
spec:
  maxReplicas: 6
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: go-hpa
  targetCPUUtilizationPercentage: 15